app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

homepage:
    path:   /
    defaults:  { _controller: AppBundle:Default:index}

coop_tilleuls_forgot_password:
    resource: '@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml'
    prefix:   '/api/forgot-password'